import { Repository } from 'typeorm';
import { Part } from './entities/part.entity';
import { Inventory } from '../inventory/entities/inventory.entity';
import { PaginatedResponseDto } from '../common/dto/paginated-response.dto';
import { SettingsService } from '../settings/settings.service';
export declare class PartsService {
    private partRepo;
    private inventoryRepo;
    private settingsSvc;
    constructor(partRepo: Repository<Part>, inventoryRepo: Repository<Inventory>, settingsSvc: SettingsService);
    findAll(page?: number, pageSize?: number, filters?: {
        classification_id?: number;
        category?: string;
        brand?: string;
        car_model?: string;
        part_type?: string;
        is_active?: boolean;
        keyword?: string;
    }): Promise<PaginatedResponseDto<{
        inventory: Inventory | {
            quantity: number;
            reservedQuantity: number;
            minStock: number;
        };
        id: number;
        oeNumber: string;
        partNameCn: string;
        partNameEn: string;
        partNameKo: string;
        classificationId: number;
        classification: import("./entities/part-classification.entity").PartClassification;
        category: string;
        subCategory: string;
        brand: string;
        carModel: string;
        engineType: string;
        modelYearFrom: number;
        modelYearTo: number;
        partType: string;
        specifications: Record<string, any>;
        unit: string;
        weightKg: number;
        dimensionsCm: string;
        hsCode: string;
        notes: string;
        isActive: boolean;
        createdBy: number;
        updatedBy: number;
        createdAt: Date;
        updatedAt: Date;
    }>>;
    findOne(id: number): Promise<{
        inventory: Inventory | null;
        id: number;
        oeNumber: string;
        partNameCn: string;
        partNameEn: string;
        partNameKo: string;
        classificationId: number;
        classification: import("./entities/part-classification.entity").PartClassification;
        category: string;
        subCategory: string;
        brand: string;
        carModel: string;
        engineType: string;
        modelYearFrom: number;
        modelYearTo: number;
        partType: string;
        specifications: Record<string, any>;
        unit: string;
        weightKg: number;
        dimensionsCm: string;
        hsCode: string;
        notes: string;
        isActive: boolean;
        createdBy: number;
        updatedBy: number;
        createdAt: Date;
        updatedAt: Date;
    }>;
    search(query: string, limit?: number): Promise<{
        quantity: number;
        id: number;
        oeNumber: string;
        partNameCn: string;
        partNameEn: string;
        partNameKo: string;
        classificationId: number;
        classification: import("./entities/part-classification.entity").PartClassification;
        category: string;
        subCategory: string;
        brand: string;
        carModel: string;
        engineType: string;
        modelYearFrom: number;
        modelYearTo: number;
        partType: string;
        specifications: Record<string, any>;
        unit: string;
        weightKg: number;
        dimensionsCm: string;
        hsCode: string;
        notes: string;
        isActive: boolean;
        createdBy: number;
        updatedBy: number;
        createdAt: Date;
        updatedAt: Date;
    }[]>;
    getCategories(): Promise<any[]>;
    create(data: any): Promise<Part>;
    update(id: number, data: any): Promise<Part>;
    remove(id: number): Promise<void>;
    batchDelete(ids: number[]): Promise<{
        deleted: number;
    }>;
    batchTranslate(ids?: number[]): Promise<{
        total: number;
        translated: number;
        failed: number;
        errors: string[];
    }>;
}
