module.exports = {
  apps: [{
    name: 'carparts-api',
    script: 'dist/main.js',
    cwd: '/www/wwwroot/carparts/backend',
    instances: 1,
    exec_mode: 'fork',
    env: {
      NODE_ENV: 'production',
      PORT: 3000,
      DB_HOST: 'localhost',
      DB_PORT: 5432,
      DB_USER: 'carparts',
      DB_PASSWORD: 'carparts123',
      DB_NAME: 'carparts',
      JWT_SECRET: 'change-this-to-a-secure-random-string',
      JWT_EXPIRES_IN: '15m',
      JWT_REFRESH_EXPIRES_IN: '7d',
      UPLOAD_DEST: '/www/wwwroot/carparts/uploads',
      MAX_FILE_SIZE: '10485760',
    },
    max_memory_restart: '1G',
    error_file: '/var/log/carparts/error.log',
    out_file: '/var/log/carparts/out.log',
    log_date_format: 'YYYY-MM-DD HH:mm:ss',
    merge_logs: true,
    autorestart: true,
    watch: false,
    max_restarts: 10,
    restart_delay: 5000,
  }],
};
