import { Repository } from 'typeorm';
import { ImageAsset } from './entities/image-asset.entity';
import { AssetTag } from './entities/asset-tag.entity';
import { AssetClassification } from './entities/asset-classification.entity';
import { Part } from '../parts/entities/part.entity';
import { ImageProcessingService } from './image-processing.service';
import { OcrService } from './ocr.service';
import { ImageRecognitionService } from './image-recognition.service';
import { SettingsService } from '../settings/settings.service';
import { PaginatedResponseDto } from '../common/dto/paginated-response.dto';
export declare class AssetsService {
    private assetRepo;
    private tagRepo;
    private classRepo;
    private partRepo;
    private imageProcessing;
    private ocrService;
    private recognitionService;
    private settingsSvc;
    private readonly logger;
    private oeLookupCache;
    constructor(assetRepo: Repository<ImageAsset>, tagRepo: Repository<AssetTag>, classRepo: Repository<AssetClassification>, partRepo: Repository<Part>, imageProcessing: ImageProcessingService, ocrService: OcrService, recognitionService: ImageRecognitionService, settingsSvc: SettingsService);
    upload(file: Express.Multer.File, data: {
        part_id?: number;
        classification_id?: number;
        category?: string;
        tag_ids?: number[];
        uploaded_by?: number;
    }): Promise<{
        tags: AssetTag[];
        id: number;
        partId: number;
        filePath: string;
        fileName: string;
        fileSize: number;
        width: number;
        height: number;
        type: string;
        mimeType: string;
        duration: number;
        ocrText: string;
        ocrStatus: string;
        category: string;
        isPrimary: boolean;
        sortOrder: number;
        classificationId: number;
        thumbnailSmallPath: string;
        thumbnailMediumPath: string;
        thumbnailLargePath: string;
        recognitionStatus: string;
        recognizedOeNumber: string;
        recognizedPartType: string;
        recognizedBrand: string;
        partNameCn: string;
        partNameEn: string;
        recognitionConfidence: number;
        recognitionResult: Record<string, any>;
        uploadedBy: number;
        createdAt: Date;
    }>;
    batchUpload(files: Express.Multer.File[], data: {
        classification_id?: number;
        uploaded_by?: number;
    }): Promise<any[]>;
    private processInBackground;
    findAll(page?: number, pageSize?: number, filters?: {
        classification_id?: number;
        tag_ids?: number[];
        keyword?: string;
        oe_number?: string;
        part_type?: string;
        brand?: string;
        part_id?: number;
        category?: string;
        type?: string;
    }): Promise<PaginatedResponseDto<ImageAsset>>;
    findOne(id: number): Promise<{
        tags: AssetTag[];
        id: number;
        partId: number;
        filePath: string;
        fileName: string;
        fileSize: number;
        width: number;
        height: number;
        type: string;
        mimeType: string;
        duration: number;
        ocrText: string;
        ocrStatus: string;
        category: string;
        isPrimary: boolean;
        sortOrder: number;
        classificationId: number;
        thumbnailSmallPath: string;
        thumbnailMediumPath: string;
        thumbnailLargePath: string;
        recognitionStatus: string;
        recognizedOeNumber: string;
        recognizedPartType: string;
        recognizedBrand: string;
        partNameCn: string;
        partNameEn: string;
        recognitionConfidence: number;
        recognitionResult: Record<string, any>;
        uploadedBy: number;
        createdAt: Date;
    }>;
    update(id: number, data: {
        classification_id?: number;
        part_id?: number;
        category?: string;
        is_primary?: boolean;
        tag_ids?: number[];
        recognized_oe_number?: string;
        recognized_part_type?: string;
        recognized_brand?: string;
        part_name_cn?: string;
        part_name_en?: string;
    }): Promise<{
        tags: AssetTag[];
        id: number;
        partId: number;
        filePath: string;
        fileName: string;
        fileSize: number;
        width: number;
        height: number;
        type: string;
        mimeType: string;
        duration: number;
        ocrText: string;
        ocrStatus: string;
        category: string;
        isPrimary: boolean;
        sortOrder: number;
        classificationId: number;
        thumbnailSmallPath: string;
        thumbnailMediumPath: string;
        thumbnailLargePath: string;
        recognitionStatus: string;
        recognizedOeNumber: string;
        recognizedPartType: string;
        recognizedBrand: string;
        partNameCn: string;
        partNameEn: string;
        recognitionConfidence: number;
        recognitionResult: Record<string, any>;
        uploadedBy: number;
        createdAt: Date;
    }>;
    remove(id: number): Promise<void>;
    batchDelete(ids: number[]): Promise<{
        deleted: number;
    }>;
    batchClassify(ids: number[], classificationId: number): Promise<{
        updated: number;
    }>;
    batchTag(ids: number[], tagIds: number[]): Promise<{
        updated: number;
    }>;
    batchUpdate(ids: number[], data: {
        recognized_oe_number?: string;
        recognized_part_type?: string;
        recognized_brand?: string;
        part_name_cn?: string;
        part_name_en?: string;
    }): Promise<{
        updated: number;
    }>;
    recognizeAsset(id: number, options: {
        ocr?: boolean;
        ai?: boolean;
        oeLookup?: boolean;
    }): Promise<{
        tags: AssetTag[];
        id: number;
        partId: number;
        filePath: string;
        fileName: string;
        fileSize: number;
        width: number;
        height: number;
        type: string;
        mimeType: string;
        duration: number;
        ocrText: string;
        ocrStatus: string;
        category: string;
        isPrimary: boolean;
        sortOrder: number;
        classificationId: number;
        thumbnailSmallPath: string;
        thumbnailMediumPath: string;
        thumbnailLargePath: string;
        recognitionStatus: string;
        recognizedOeNumber: string;
        recognizedPartType: string;
        recognizedBrand: string;
        partNameCn: string;
        partNameEn: string;
        recognitionConfidence: number;
        recognitionResult: Record<string, any>;
        uploadedBy: number;
        createdAt: Date;
    }>;
    batchRecognize(ids: number[], options: {
        ocr?: boolean;
        ai?: boolean;
        oeLookup?: boolean;
    }): Promise<{
        processed: number;
        failed: number;
        errors: string[] | undefined;
    }>;
    undoRecognize(id: number): Promise<{
        tags: AssetTag[];
        id: number;
        partId: number;
        filePath: string;
        fileName: string;
        fileSize: number;
        width: number;
        height: number;
        type: string;
        mimeType: string;
        duration: number;
        ocrText: string;
        ocrStatus: string;
        category: string;
        isPrimary: boolean;
        sortOrder: number;
        classificationId: number;
        thumbnailSmallPath: string;
        thumbnailMediumPath: string;
        thumbnailLargePath: string;
        recognitionStatus: string;
        recognizedOeNumber: string;
        recognizedPartType: string;
        recognizedBrand: string;
        partNameCn: string;
        partNameEn: string;
        recognitionConfidence: number;
        recognitionResult: Record<string, any>;
        uploadedBy: number;
        createdAt: Date;
    }>;
    batchUndoRecognize(ids: number[]): Promise<{
        processed: number;
        failed: number;
    }>;
    private normalizeOeNumber;
    private parseOcrText;
    private deleteAssetFiles;
    getClassifications(): Promise<AssetClassification[]>;
    createClassification(data: {
        name: string;
        parent_id?: number;
        description?: string;
    }): Promise<{
        name: string;
        parentId: number | undefined;
        description: string;
    } & AssetClassification>;
    deleteClassification(id: number): Promise<void>;
    getTags(): Promise<AssetTag[]>;
    createTag(data: {
        name: string;
        color?: string;
    }): Promise<{
        name: string;
        color: string;
    } & AssetTag>;
    deleteTag(id: number): Promise<void>;
    cropImage(id: number, x: number, y: number, width: number, height: number): Promise<ImageAsset>;
    addWatermark(id: number, text: string): Promise<ImageAsset>;
    private lookupBrandByOE;
    lookupPartNameByOE(oeNumber: string, context?: {
        brand?: string;
        partType?: string;
    }): Promise<{
        partNameCn: string;
        partNameEn: string;
        brand: string;
        partType: string;
    } | null>;
}
